version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    env_file: ${PWD-.}/config/db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ${PWD-.}/mysql-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ${PWD-.}/redis:/data
    restart: unless-stopped
  grafana:
    image: philhawthorne/docker-influxdb-grafana:edge
    volumes:
      - ${PWD-.}/metrics/influxdb:/var/lib/influxdb
      - ${PWD-.}/metrics/grafana:/var/lib/grafana
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
  nwnxee-server:
    image: nwnxee/unified:latest
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    links:
      - "db:db"
      - "redis:redis"
      - "grafana:grafana"
    depends_on:
      - db
      - redis
    volumes:
      - ${PWD-.}/server/:/nwn/home
    restart: always
    ports:
      - "5121:5121/udp"
